version: '3.0'
services:
  node:
    build: .
    ports: -${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
  postgres:
    builds: ./postgres/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
