name: nodejs2024q3
services:
  server:
    image: surface74/rest-server
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    environment:
      PORT: ${PORT}
      LOAD_MOCK_DATA: ${LOAD_MOCK_DATA}
      POSTGRES_DOMAIN: ${POSTGRES_DOMAIN}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - frontend
    depends_on:
      - postgres
  postgres:
    image: surface74/postgres
    container_name: postgres_container
    command:
      - 'postgres'
      - '--logging_collector=true'
      - '--log_destination=syslog'
      - '--log_directory=/usr/app/postgres-data/pg_log'
      - '--log_rotation_age=60'
    restart: unless-stopped
    env_file: .env
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: '/usr/app/postgres-data/'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - ./postgres-data:/usr/app/postgres-data/
    networks:
      - frontend

volumes:
  postgres-data:

networks:
  frontend:
    driver: bridge
